### ISSUE TITLE
openMSE 1.0.0: no defaults specified for certain slots in built-in Obs objects (e.g. "sigmaRbiascv", "Eobs", "Ebiascv")

### ISSUE THREAD

**Issue by Nikolai-Klibansky** [Blue-Matter/openMSE#1] opened 2021-12-10 20:24 UTC
Hi guys,

This is a pretty minor issue, but it seems that default values of "sigmaRbiascv", "Eobs", and "Ebiascv" are completely missing from available Obs objects:
` "Generic_Obs"        "Imprecise_Biased"   "Imprecise_Unbiased" "Perfect_Info"       "Precise_Biased"     "Precise_Unbiased"`

This is the behavior I see when I look for the value in one of these slots.
`> slot(Generic_Obs,"sigmaRbiascv")`
`Error in slot(Generic_Obs, "sigmaRbiascv") : `
  `no slot of name "sigmaRbiascv" for this object of class "Obs"`

I can still specify values for these slots and the errors go away, but I think the intent was to have defaults for all of these slots.

All best,
Nikolai

**Comment by Nikolai-Klibansky** [comment] 2021-12-10 21:13
Okay, I'll comment on my own issue.
I get different behavior if I specify the package:
`> slot(MSEtool::Generic_Obs,"sigmaRbiascv")`
`[1] 0.1`

I'm not really sure what to make of that.

**Comment by quang-huynh** [comment] 2021-12-14 04:48
Hi @nikolaifish I wasn't able to reproduce the issue as `library(MSEtool); slot(Generic_Obs,"sigmaRbiascv")` returned `0.1` as expected. Which version of MSEtool are you using?

**Comment by Nikolai-Klibansky** [comment] 2021-12-14 15:03
It was 3.2.0. I see now that there is a 3.3.0. I'll update and see if I get
the same error.

Nikolai

**Comment by AdrianHordyk** [comment] 2021-12-14 18:46
Also make sure `DLMtool` package is updated; the error looks like it is from an older version of `DLMtool`

**Comment by Nikolai-Klibansky** [comment] 2021-12-14 19:18
I just updated all of my packages and I still got the same error. But when
I removed DLMtool specifically and then reinstalled openMSE the error went
away. So I guess the old version of DLMtool was the culprit. I would have
thought using the update packages button in RStudio would solve that but
maybe DLMtool was preceding openMSE in the search path and the old Obs
objects were masking the new ones?

Thanks for your help! Sorry for the trouble.

Nikolai

**Comment by AdrianHordyk** [comment] 2021-12-14 20:04
No probs. 
The update packages feature doesn't always work as expected. Manually uninstalling and re-installing the packages is often the best approach.

I'll close the issue, but re-open or submit a new issue if you continue to have problems.

**Closed as completed by AdrianHordyk** 2021-12-14 20:04 UTC
